name: Build Nightly Wheels

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  schedule:
    # The notifications for scheduled workflows are sent to the user who
    # last modified the cron syntax in the workflow file.
    # Trigger the workflow at 03:00(CST) every day.
    - cron:  '00 19 * * *'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-nightly-wheel.yml'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_wheels_linux_x86_64:
    runs-on: [self-hosted, linux, x64]
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Clean the tool directory for self-hosted runner
        run: |
          rm -rf /__w/_tool/Python

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.23.3

      - name: Prepare for linux
        run: |
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV

      - name: Set nightly wheel version
        run: |
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          short_sha=$(git rev-parse --short HEAD)
          echo "${version}+${short_sha}" > ${GITHUB_WORKSPACE}/NEUG_VERSION

      - name: Build wheels
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
          export BUILD_TYPE=RELEASE
          python3 -m cibuildwheel ./tools/python_bind --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        if: false
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: wheelhouse/
          verbose: true
          skip_existing: true # Skip existing wheels to avoid errors if the same wheel is already published, to update the wheel for a specific version, add -{number} to the filename and
          # update it manually

      - name: Clean all installed python packages
        run: |
          python3 -m pip freeze | xargs python3 -m pip uninstall -y || true
    
      - name: Run simple test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        env:
          TMP_DIR: ${{ github.workspace }}/${{ github.run_id }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip uninstall -y neug || echo "Uninstalled neug if it was installed"
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          python3 -m pip install neug==${version} || echo "Failed to install neug ${version}"
          rm -rf ${TMP_DIR}/test_example
          GLOG_v=10 python3 tools/python_bind/example/simple_example.py example_dataset/modern_graph ${TMP_DIR}/test_example

      - name: Run NeuG-Cli test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        run: |
          neug-cli --help
          neug-cli --version

  build_wheels_linux_arm64:
    runs-on: [self-hosted, linux, arm64]
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Clean the tool directory for self-hosted runner
        run: |
          rm -rf /__w/_tool/Python

      - name: Setup Python 3.13
        if: runner.name != 'arm64-1'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.23.3

      - name: Prepare for linux
        run: |
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV

      - name: Set nightly wheel version
        run: |
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          short_sha=$(git rev-parse --short HEAD)
          echo "${version}+${short_sha}" > ${GITHUB_WORKSPACE}/NEUG_VERSION

      - name: Build wheels
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)
          export BUILD_TYPE=RELEASE
          python3 -m cibuildwheel ./tools/python_bind --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        if: false
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: wheelhouse/
          verbose: true
          skip_existing: true # Skip existing wheels to avoid errors if the same wheel is already published, to update the wheel for a specific version, add -{number} to the filename and
          # update it manually

      - name: Clean all installed python packages
        run: |
          python3 -m pip freeze | xargs python3 -m pip uninstall -y || true
    
      - name: Run simple test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        env:
          TMP_DIR: ${{ github.workspace }}/${{ github.run_id }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip uninstall -y neug || echo "Uninstalled neug if it was installed"
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          python3 -m pip install neug==${version} || echo "Failed to install neug ${version}"
          rm -rf ${TMP_DIR}/test_example
          GLOG_v=10 python3 tools/python_bind/example/simple_example.py example_dataset/modern_graph ${TMP_DIR}/test_example

      - name: Run NeuG-Cli test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        run: |
          neug-cli --help
          neug-cli --version

  build_wheels_macos_x86_64:
    runs-on: macos-15-intel
    if: false
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Only run install_dep.sh on macos system
      - name: Install dependencies
        run: |
          bash scripts/install_deps.sh

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.23.3

      - name: Prepare for macos
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=10.15" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET"
          source ~/.neug_env
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV

      - name: Set nightly wheel version
        run: |
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          short_sha=$(git rev-parse --short HEAD)
          echo "${version}+${short_sha}" > ${GITHUB_WORKSPACE}/NEUG_VERSION

      - name: Build wheels
        run: |
          source ~/.neug_env
          export CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.ncpu)
          export BUILD_TYPE=RELEASE
          python3 -m cibuildwheel ./tools/python_bind --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        if: false
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: wheelhouse/
          verbose: true
          skip_existing: true # Skip existing wheels to avoid errors if the same wheel is already published, to update the wheel for a specific version, add -{number} to the filename and
          # update it manually

      - name: Clean all installed python packages
        run: |
          python3 -m pip freeze | xargs python3 -m pip uninstall -y || true
    
      - name: Run simple test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        env:
          TMP_DIR: ${{ github.workspace }}/${{ github.run_id }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip uninstall -y neug || echo "Uninstalled neug if it was installed"
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          python3 -m pip install neug==${version} || echo "Failed to install neug ${version}"
          rm -rf ${TMP_DIR}/test_example
          GLOG_v=10 python3 tools/python_bind/example/simple_example.py example_dataset/modern_graph ${TMP_DIR}/test_example

      - name: Run NeuG-Cli test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        run: |
          neug-cli --help
          neug-cli --version

  build_wheels_macos_aarch64:
    runs-on: macos-15
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Only run install_dep.sh on macos system
      - name: Install dependencies
        run: |
          bash scripts/install_deps.sh

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.23.3

      - name: Prepare for macos
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET"
          source ~/.neug_env
          echo "CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV

      - name: Set nightly wheel version
        run: |
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          short_sha=$(git rev-parse --short HEAD)
          echo "${version}+${short_sha}" > ${GITHUB_WORKSPACE}/NEUG_VERSION

      - name: Build wheels
        run: |
          source ~/.neug_env
          export CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.ncpu)
          export BUILD_TYPE=RELEASE
          python3 -m cibuildwheel ./tools/python_bind --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        if: false
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ github.sha }}
          path: ./wheelhouse/*.whl

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: wheelhouse/
          verbose: true
          skip_existing: true # Skip existing wheels to avoid errors if the same wheel is already published, to update the wheel for a specific version, add -{number} to the filename and
          # update it manually

      - name: Clean all installed python packages
        run: |
          python3 -m pip freeze | xargs python3 -m pip uninstall -y || true

      - name: Run simple test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        env:
          TMP_DIR: ${{ github.workspace }}/${{ github.run_id }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip uninstall -y neug || echo "Uninstalled neug if it was installed"
          version=$(cat ${GITHUB_WORKSPACE}/NEUG_VERSION)
          python3 -m pip install neug==${version} || echo "Failed to install neug ${version}"
          rm -rf ${TMP_DIR}/test_example
          GLOG_v=10 python3 tools/python_bind/example/simple_example.py example_dataset/modern_graph ${TMP_DIR}/test_example

      - name: Run NeuG-Cli test
        if: github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.repository == 'alibaba/neug'
        run: |
          neug-cli --help
          neug-cli --version
