name: Generate Documentation

on:
    pull_request:
      branches:
        - main
      paths:
        - 'doc/**'
        - 'tools/java_driver/**'
        - '.github/workflows/docs.yml'


concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: [ubuntu-22.04]
    container:
      image: neug-registry.cn-hongkong.cr.aliyuncs.com/neug/neug-dev:v0.1.1
      # options: --user root

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Setup Java and Maven
      uses: s4u/setup-maven-action@v1.19.0
      with:
        java-version: '17'
        maven-version: '3.9.6'

    - name: Build Documentation
      run: |
        sudo apt update
        sudo apt install -y doxygen graphviz
        cd ${GITHUB_WORKSPACE}/tools/java_driver
        mvn -DskipTests javadoc:javadoc
        cd ${GITHUB_WORKSPACE}/tools/python_bind
        python3 -m pip  install -r requirements.txt
        python3 -m pip  install -r requirements_dev.txt
        cd ${GITHUB_WORKSPACE}/doc
        . /home/neug/.neug_env
        make dependencies
        make html
        mkdir -p ${GITHUB_WORKSPACE}/doc/build/html/reference/java_api
        cp -r ${GITHUB_WORKSPACE}/tools/java_driver/target/site/apidocs ${GITHUB_WORKSPACE}/doc/build/html/reference/java_api/
