name: Format Check

on:
  workflow_call:
    inputs:
      is_pull_request:
        type: boolean
        default: false
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}-format-check-${{ github.event.number || github.head_ref || github.sha }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  check-format:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Conventional PR Check
      if: inputs.is_pull_request || github.event_name == 'pull_request'
      uses: amannn/action-semantic-pull-request@v5
      id: pr-convention
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # Types allowed (newline-delimited).
        # Default: https://github.com/commitizen/conventional-commit-types
        types: |
          build
          ci
          docs
          feat
          fix
          perf
          refactor
          test
          chore
        # Scopes allowed (newline-delimited).
        scopes: |
          core
          python
          src
        # A scope can be not provided.
        requireScope: false
        disallowScopes: |
          release
          [A-Z]+
        # If the PR contains one of these newline-delimited labels, the
        # validation is skipped.
        ignoreLabels: |
          bot
          ignore-semantic-pull-request

    - name: Comments if PR Title is not conventional
      id: lint_pr_title
      uses: marocchino/sticky-pull-request-comment@v2
      # When the previous steps fails, the workflow would stop. By adding this
      # condition you can continue the execution with the populated error message.
      if: (inputs.is_pull_request || github.event_name == 'pull_request') && always() && (steps.pr-convention.outputs.error_message != null)
      with:
        header: pr-title-lint-error
        message: |
          Hey there and thank you for opening this pull request! 👋🏼

          We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) \
          and it looks like your proposed title needs to be adjusted.

          Details:
          ```
          ${{ steps.pr-convention.outputs.error_message }}
          ```


      # Delete a previous comment when the issue has been resolved
    - name: Delete Comment if PR Title is conventional
      if: (inputs.is_pull_request || github.event_name == 'pull_request') && steps.lint_pr_title.outputs.error_message == null
      uses: marocchino/sticky-pull-request-comment@v2
      with:   
        header: pr-title-lint-error
        delete: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Get PR Changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          docs:
            - 'docs/**'    

    - name: Cpp Format and Lint Check
      run: |
        # install clang-format
        sudo curl -L https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-22538c65/clang-format-8_linux-amd64 --output /usr/local/bin/clang-format
        sudo chmod +x /usr/local/bin/clang-format

        # validate format
        function prepend() { while read line; do echo "${1}${line}"; done; }

        # except for files generated by protobuf
        find ./include ./src ./tests ./tools -name "*.h" ! -name "*pb.h" ! -name "*pb.cc" | xargs clang-format -i --style=file

        GIT_DIFF=$(git diff --ignore-submodules)
        if [[ -n $GIT_DIFF ]]; then
            echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
            echo "| clang-format failures found!"
            echo "|"
            echo "$GIT_DIFF" | prepend "| "
            echo "|"
            echo "| Run: "
            echo "|    mkdir build && cd build && cmake .."
            echo "|    make neug_clformat"
            echo "|"
            echo "| to fix this error."
            echo "|"
            echo "| Ensure you are working with clang-format-8, which can be obtained from"
            echo "| sudo curl -L https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-22538c65/clang-format-8_linux-amd64 --output /usr/local/bin/clang-format"
            echo "| sudo chmod +x /usr/local/bin/clang-format"
            echo "|"
            echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
            exit 1
        fi
    - name: Python Format and Lint Check
      run: |
        pushd ${GITHUB_WORKSPACE}/tools/python_bind
        python3 -m pip  install -r requirements_dev.txt
        python3 -m pip  install -r requirements.txt

        function print_error() {
            echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
            echo "| $1"
            echo "|"
            echo "| Please cd into $2 and run 'python3 -m $3 .' to fix it"
            echo "|"
            echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        }

        (python3 -m isort --check --diff .) || (print_error "isort check failed" "tools/python_bind" "isort" && exit 1)
        (python3 -m black --check --diff .) || (print_error "black check failed" "tools/python_bind" "black" && exit 1)
        (python3 -m flake8 .) || (print_error "flake8 check failed" "tools/python_bind" "flake8" && exit 1)

        popd

        pushd ${GITHUB_WORKSPACE}/tests/e2e
        (python3 -m isort --check --diff .) || (print_error "isort check failed" "tests/e2e" "isort" && exit 1)
        (python3 -m black --check --diff .) || (print_error "black check failed" "tests/e2e" "black" && exit 1)
        (python3 -m flake8 .) || (print_error "flake8 check failed" "tests/e2e" "flake8" && exit 1)
        popd

        
