# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0c\x63ommon.proto\x12\x06\x63ommon"\x06\n\x04None"\x18\n\x08I32Array\x12\x0c\n\x04item\x18\x01 \x03(\x05"\x18\n\x08I64Array\x12\x0c\n\x04item\x18\x01 \x03(\x03"\x1b\n\x0b\x44oubleArray\x12\x0c\n\x04item\x18\x01 \x03(\x01"\x1b\n\x0bStringArray\x12\x0c\n\x04item\x18\x01 \x03(\t">\n\x04Pair\x12\x1a\n\x03key\x18\x01 \x01(\x0b\x32\r.common.Value\x12\x1a\n\x03val\x18\x02 \x01(\x0b\x32\r.common.Value"\'\n\tPairArray\x12\x1a\n\x04item\x18\x01 \x03(\x0b\x32\x0c.common.Pair"0\n\x08NameOrId\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x0c\n\x02id\x18\x02 \x01(\x05H\x00\x42\x06\n\x04item"\x16\n\x06\x44\x61te32\x12\x0c\n\x04item\x18\x01 \x01(\x05"\x16\n\x06Time32\x12\x0c\n\x04item\x18\x01 \x01(\x05"\x19\n\tTimestamp\x12\x0c\n\x04item\x18\x01 \x01(\x03"\xec\x03\n\x05Value\x12\x11\n\x07\x62oolean\x18\x02 \x01(\x08H\x00\x12\r\n\x03i32\x18\x03 \x01(\x05H\x00\x12\r\n\x03i64\x18\x04 \x01(\x03H\x00\x12\r\n\x03\x66\x36\x34\x18\x05 \x01(\x01H\x00\x12\r\n\x03str\x18\x06 \x01(\tH\x00\x12\x0e\n\x04\x62lob\x18\x07 \x01(\x0cH\x00\x12%\n\ti32_array\x18\x08 \x01(\x0b\x32\x10.common.I32ArrayH\x00\x12%\n\ti64_array\x18\t \x01(\x0b\x32\x10.common.I64ArrayH\x00\x12(\n\tf64_array\x18\n \x01(\x0b\x32\x13.common.DoubleArrayH\x00\x12(\n\tstr_array\x18\x0b \x01(\x0b\x32\x13.common.StringArrayH\x00\x12\'\n\npair_array\x18\x0c \x01(\x0b\x32\x11.common.PairArrayH\x00\x12\x1c\n\x04none\x18\r \x01(\x0b\x32\x0c.common.NoneH\x00\x12\x1e\n\x04\x64\x61te\x18\x0e \x01(\x0b\x32\x0e.common.Date32H\x00\x12\x1e\n\x04time\x18\x0f \x01(\x0b\x32\x0e.common.Time32H\x00\x12&\n\ttimestamp\x18\x10 \x01(\x0b\x32\x11.common.TimestampH\x00\x12\r\n\x03u32\x18\x11 \x01(\rH\x00\x12\r\n\x03u64\x18\x12 \x01(\x04H\x00\x12\r\n\x03\x66\x33\x32\x18\x13 \x01(\x02H\x00\x42\x06\n\x04itemB+\n!com.alibaba.graphscope.gaia.protoB\x06\x43ommonb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "common_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n!com.alibaba.graphscope.gaia.protoB\006Common"
    _NONE._serialized_start = 24
    _NONE._serialized_end = 30
    _I32ARRAY._serialized_start = 32
    _I32ARRAY._serialized_end = 56
    _I64ARRAY._serialized_start = 58
    _I64ARRAY._serialized_end = 82
    _DOUBLEARRAY._serialized_start = 84
    _DOUBLEARRAY._serialized_end = 111
    _STRINGARRAY._serialized_start = 113
    _STRINGARRAY._serialized_end = 140
    _PAIR._serialized_start = 142
    _PAIR._serialized_end = 204
    _PAIRARRAY._serialized_start = 206
    _PAIRARRAY._serialized_end = 245
    _NAMEORID._serialized_start = 247
    _NAMEORID._serialized_end = 295
    _DATE32._serialized_start = 297
    _DATE32._serialized_end = 319
    _TIME32._serialized_start = 321
    _TIME32._serialized_end = 343
    _TIMESTAMP._serialized_start = 345
    _TIMESTAMP._serialized_end = 370
    _VALUE._serialized_start = 373
    _VALUE._serialized_end = 865
# @@protoc_insertion_point(module_scope)
