# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import basic_type_pb2 as basic__type__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ntype.proto\x12\x06\x63ommon\x1a\x0c\x63ommon.proto\x1a\x10\x62\x61sic_type.proto\x1a\x1egoogle/protobuf/wrappers.proto"\xa9\x04\n\rGraphDataType\x12:\n\x0b\x65lement_opt\x18\x01 \x01(\x0e\x32%.common.GraphDataType.GraphElementOpt\x12?\n\x0fgraph_data_type\x18\x02 \x03(\x0b\x32&.common.GraphDataType.GraphElementType\x1a\x82\x01\n\x11GraphElementLabel\x12\r\n\x05label\x18\x01 \x01(\x05\x12.\n\tsrc_label\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12.\n\tdst_label\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x1aZ\n\x15GraphElementTypeField\x12!\n\x07prop_id\x18\x01 \x01(\x0b\x32\x10.common.NameOrId\x12\x1e\n\x04type\x18\x02 \x01(\x0b\x32\x10.common.DataType\x1a\x86\x01\n\x10GraphElementType\x12\x36\n\x05label\x18\x01 \x01(\x0b\x32\'.common.GraphDataType.GraphElementLabel\x12:\n\x05props\x18\x02 \x03(\x0b\x32+.common.GraphDataType.GraphElementTypeField"1\n\x0fGraphElementOpt\x12\n\n\x06VERTEX\x10\x00\x12\x08\n\x04\x45\x44GE\x10\x01\x12\x08\n\x04PATH\x10\x02"h\n\nIrDataType\x12%\n\tdata_type\x18\x01 \x01(\x0b\x32\x10.common.DataTypeH\x00\x12+\n\ngraph_type\x18\x02 \x01(\x0b\x32\x15.common.GraphDataTypeH\x00\x42\x06\n\x04typeB-\n!com.alibaba.graphscope.gaia.protoB\x08\x44\x61taTypeb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "type_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n!com.alibaba.graphscope.gaia.protoB\010DataType"
    )
    _GRAPHDATATYPE._serialized_start = 87
    _GRAPHDATATYPE._serialized_end = 640
    _GRAPHDATATYPE_GRAPHELEMENTLABEL._serialized_start = 230
    _GRAPHDATATYPE_GRAPHELEMENTLABEL._serialized_end = 360
    _GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD._serialized_start = 362
    _GRAPHDATATYPE_GRAPHELEMENTTYPEFIELD._serialized_end = 452
    _GRAPHDATATYPE_GRAPHELEMENTTYPE._serialized_start = 455
    _GRAPHDATATYPE_GRAPHELEMENTTYPE._serialized_end = 589
    _GRAPHDATATYPE_GRAPHELEMENTOPT._serialized_start = 591
    _GRAPHDATATYPE_GRAPHELEMENTOPT._serialized_end = 640
    _IRDATATYPE._serialized_start = 642
    _IRDATATYPE._serialized_end = 746
# @@protoc_insertion_point(module_scope)
